apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nz171psw4-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-e078763d77.uwxi.p3.openshiftapps.com/rhtap/rhtap-qe-dotnet-basic:d172f3ef05537c36c29dbacc8ca071e3e901f052@sha256:97402f20c4fe546b1b764cac71da643b3fcc057e3b338b020bc974738ac63d49
          name: container-image
